name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GLOBAL_NUM: ${{ secrets.NUMBER }}

    steps:
      - uses: actions/checkout@v4

      - name: Print lower
        if: github.event.number < env.GLOBAL_NUM
        run: echo "lower"

      - name: Print higher
        if: github.event.number > env.GLOBAL_NUM
        run: echo "higher"

      - name: Print correct
        if: github.event.number == env.GLOBAL_NUM
        run: echo "correct"
